<script id="swym-fetch-template" type="x-tmpl-mustache">
  <div class="swym-inner">
      <div class="swym-image">
        <a href="{{du}}">
            <img src="{{iu}}" />
            <div class="swym-viewed-icon swym-background-color {{deviceType}}">
                <i class="swym-icon-sprite"></i>
                <span>{{dateStr}}</span>
                <span class="swym-background swym-background-color"></span>
            </div>
        </a>
      </div>
      <div class="swym-actions">
          {{#inwishlist}}
          <a href="#" class="swym-wishlist" alt="Add To Wishlist">
              <i class="swym-icon-sprite"></i>
          </a>
          {{/inwishlist}}
          <a href="javascript:void(0);" class="swym-remove" onclick="deleteItem('{{_id}}');" alt="Remove Item">
              <i class="swym-icon-sprite"></i>
          </a>
      </div>
      <div class="swym-information">
          <div class="swym-title">
              <a href="{{du}}">{{dt}}</a>
          </div>
      <div class="swym-price swym-text-color"><span class="swym-old">{{op}}</span>{{pr}}</div>
      <div class="swym-viewed-label">{{dateStr}}</div>
      {{#incart}}
      <a href="{{du}}" class="swym-add-to-cart" id="swym-add-to-cart">
      <i class="swym-icon-sprite"></i> In Your Cart
      </a>
      {{/incart}}
      </div>
  </div>
</script>
<script id="swym-email-template" type="x-tmpl-mustache">
   <a href="javascript:void(0);" onClick="_changeTab('settings');">
      <i class="swym-icon-sprite"></i>
      <span>{{email}}</span>
   </a>
</script>
<script id="swym-toast-template" type="x-tmpl-mustache">
  <div id="swym-notification-header" class="swym-notification-header swym-background-color">
      <i class="swym-icon swym-icon-sprite"></i>
      <strong id="swym-notification-title" onclick="launchNotepadFromNotification();" class="swym-title">{{hdr}}</strong>
      <a href="javascript:void(0);" onclick="_closeNotification();" class="swym-close">
          <i class="swym-icon-sprite"></i> Close
      </a>
  </div>
  <div class="swym-notification-content" id="swym-notification-content">
      <div class="swym-item">
          <div class="swym-inner">
              <div class="swym-image">
                <a href="{{du}}">
                    <img src="{{iu}}" />
                </a>
              </div>
              <div class="swym-information">
                  <div class="swym-title">
                      <a href="{{du}}">{{dt}}</a>
                  </div>
                  <div class="swym-price">
                      <span class="swym-old">{{op}}</span> {{pr}}
                  </div>
                  <a href="javascript:void(0);" onclick="launchNotepadFromNotification();" class="swym-view-history">View Your Shopping History</a>
              </div>
          </div>
      </div>
      <div class="swym-powered-by">
          Powered By Swym
      </div>
  </div>
</script>
<script id="swym-device-template" type="x-tmpl-mustache">
   <div class="swym-inner">
      <div class="swym-image">
         <i class="{{deviceType}} swym-background-color"></i>
      </div>
      <div class="swym-information">
         <div class="swym-title swym-text-color">{{dcat}}</div>
         <div class="swym-last-accessed">Created On: {{dateStr}}</div>
      </div>
   </div>
</script>
<script id='swym-settings-auth-template' type="x-tmpl-mustache">
  <div class="swym-auth" id="swym-auth">
      <p>Fetch history from my other devices</p>
      <form action="#" id="swym-email-auth-form">
          <i class="swym-icon-sprite"></i>
          <input type="email" name="swym-email-auth" id="swym-email-auth-input" class="swym-input" placeholder="Enter your email address" />
          <button type="button" id="swym-email-auth-button" class="swym-button swym-background-color loader">Connect</button>
      </form>
  </div>
</script>
<script type="x-tmpl-mustache" id='swym-welcome-template'>
   <strong class="swym-text-color">The {{nptitle}} is Your Shopping Assistant</strong>
   <p>We will keep track of all your shopping activity making it easily accessible from all your devices. You won't have to lose time searching for that shirt you saw on your lunchbreak that you just can’t live without. </p>
   <button type="button" onClick="_changeTab('items');" class="swym-button swym-background-color">Access {{nptitle}}</button>
   <p>
     <!-- <small><a class="swym-text-color" href="#">I don’t need a shopping assistant, please turn {{nptitle}} off</a></small> -->
   </p>
</script>

<div id="swym-plugin">
    <div id="swym-anchor">
        <a class="swym-background-color" href="javascript:void(0);" onClick="_openModal();" id="notepad-anchor-title">
            <i class="swym-icon-sprite swym-icon"></i></a>
    </div>
    <script type="text/javascript">
        swymRenderNotepadAnchor();
    </script>
    <div id="swym-modal">
        <div id="swym-modal-header" class="swym-modal-header swym-background-color">
            <strong class="swym-title" id="notepad-title"></strong>
            <span class="swym-tag">Your Personal Shopping Assistant</span>
            <a href="javascript:void(0);" onClick="_closeModal();" class="swym-close">
                <i class="swym-icon-sprite"></i> Close
            </a>
        </div>
        <div id="swym-toolbar-top" class="swym-toolbar-top">
            <ul class="swym-actions">
                <li class="swym-arrow-left">
                    <a href="javascript:void(0);" onClick="searchClear();">
                        <i class="swym-icon-sprite"></i>
                    </a>
                </li>
                <li class="swym-settings">
                    <a href="javascript:void(0);" onClick="_changeTab('settings');">
                        <i class="swym-icon-sprite"></i>
                    </a>
                </li>
                <li class="swym-refresh">
                    <a href="javascript:void(0);" onClick="searchSubmit();">
                        <i class="swym-icon-sprite"></i>
                    </a>
                </li>
                <li class="swym-help">
                    <a href="javascript:void(0);" onClick="_changeTab('welcome');">
                        <i class="swym-icon-sprite"></i>
                    </a>
                </li>
                <li>
                    <span class="swym-separator"></span>
                </li>
                <li class="swym-user" id="swym-user"></li>
                <li class="swym-search">
                    <a href="javascript:void(0);" onClick="toggleSearch();">
                        <i class="swym-icon-sprite"></i>
                    </a>
                </li>
            </ul>
            <div id="swym-search-container" class="swym-search-container">
                <form action="#" method="get" name="swymHistorySearch" onSubmit="searchSubmit(); return false;" autocomplete="off">
                    <input type="search" name="swym-search" class="swym-input" id="swymSearch" onkeydown="searchKeyDown();" placeholder="Search my notepad..." />
                    <button type="button" onClick="searchSwymNotepad(swymHistorySearch.swymSearch.value);">
                        <i class="swym-icon-sprite"></i> Search
                    </button>
                </form>
            </div>
        </div>
        <div id="swym-modal-content" class="swym-modal-content">
            <div id="swym-settings-container" class="swym-settings-container">
                <strong class="swym-heading" id="swym-devices-heading">Devices</strong>
                <p>Devices where you recently accessed your shopping history</p>
                <ul class="swym-device-grid" id="swym-device-grid"></ul>
                <!--
                <button type="button" class="swym-button swym-background-color">Clear notepad history</button>
                -->
            </div>
            <div id="swym-items-container">
                <ul id="swym-item-grid" class="swym-item-grid"></ul>
            </div>
            <div id="swym-welcome-container" class="swym-welcome-container">
            </div>
        </div>
    </div>
    <div id="swym-notification">
        <div id="swym-notification-header" class="swym-notification-header swym-background-color">
            <i class="swym-icon swym-icon-sprite"></i>
            <strong id="swym-notification-title" onclick="launchNotepadFromNotification();" class="swym-title">A product you recently added to your shopping cart is now on sale.</strong>
            <a href="javascript:void(0);" onclick="_closeNotification();" class="swym-close">
                <i class="swym-icon-sprite"></i> Close
            </a>
        </div>
        <div id="swym-notification-content" class="swym-notification-content">
            <div class="swym-item">
                <div class="swym-inner">
                    <div class="swym-image">
                        <a href="#">
                        </a>
                    </div>
                    <div class="swym-information">
                        <div class="swym-title swym-text-color">
                            <a href="#">Nolita Cami</a>
                        </div>
                        <div class="swym-price swym-text-color">
                            <span class="swym-old">$130.00</span> $150.00
                        </div>
                        <a href="javascript:void(0);" class="swym-view-history swym-text-color" onclick="launchNotepadFromNotification();">View Your Shopping History</a>
                    </div>
                </div>
            </div>
            <div class="swym-powered-by">
                Powered By Swym
            </div>
        </div>
    </div>
    <div id="swym-overlay" onClick="_closeModal();"></div>
</div>

<script type="text/javascript">
    setupNotepadUX();
</script>

