<?php $isSecure = Mage::app()->getStore()->isCurrentlySecure(); ?>
<input type="hidden" id="initswymurl" value="<?php echo $isSecure?Mage::getUrl('notepad/index/initswym',array('_secure'=>true)) : Mage::getUrl('notepad/index/initswym') ?>">
<input type="hidden" id="swymauthurl" value="<?php echo $isSecure?Mage::getUrl('notepad/index/authenticateuser',array('_secure'=>true)) : Mage::getUrl('notepad/index/authenticateuser') ?>">
<input type="hidden" id="updateswymcallurl" value="<?php echo Mage::getUrl('notepad/index/swymcalljs') ?>">

<script type="text/javascript">
  _swrc('Callback', function(){
    initSwym(); //swym-magento.js
    window._swat.triggerNotify(<?php echo $this->getPageView() ?>);
    <?php if($data=$this->getProductView()){ ?>
  	window._swat.trackPageview(<?php echo $data ?>);
      <?php if($this->getAddToWishlist()){ ?>
    	window._swat.addToWishList(<?php echo $this->getAddToWishlist() ?>,function(){
        setTimeout(function(){
    		  document.getElementsByClassName('link-wishlist')[0].className=document.getElementsByClassName('link-wishlist')[0].className+' disabled';
    	  }, 1000);
      });
      <?php } ?>
    <?php } ?>
    <?php if($data=$this->getCategoryView()){ ?>
    	window._swat.trackPageview(<?php echo $data ?>);
    <?php } ?>
    <?php if($coupons=$this->getAddCoupon()){
    	foreach($coupons as $coupon)
    	{
     ?>
    	window._swat.addToCoupon(<?php echo $coupon ?>,function(r) { console.log('add coupon'); },{  uri : 'https://www.google.com/search?q=reminder'})
    <?php
    	}
    }
    ?>
  });
</script>
<script type="text/javascript">
		noteIsMobile='<?php echo $this->isMobile()?'1':'0'; ?>';
</script>
